[package]
name = "openapi-route-axum"
description = "Axum and Swagger UI integration for openapi-route"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
openapi-route.workspace = true

[build-dependencies]
ureq.workspace = true
flate2.workspace = true
tar.workspace = true
sha2.workspace = true
