[package]
name = "openapi-route"
description = "Explicit, handler-local OpenAPI route metadata and document generation"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
inventory.workspace = true
openapi-route-macros.workspace = true
serde_json.workspace = true
utoipa.workspace = true

[build-dependencies]
rhusky = "0.0.6"
